# Generated by Django 3.0.8 on 2021-01-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='noOf5mRDTTestedFeverCases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='noOf5mRDTTestedPositiveFeverCases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='noOfU5mRDTTestedFeverCases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='noOfU5mRDTTestedPositiveFeverCases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='totalNoOfFeverCases',
            field=models.IntegerField(),
        ),
    ]
